### ISSUE TITLE
Deprecated selectors on Atom v1.13.x

### ISSUE THREAD

**Issue by sectsect** [mmcbride1007/github-2016-syntax#4]
In `github-2016-syntax/index.less`:

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

<img width="758" alt="capture 2017-01-28 at 17 50 29" src="https://cloud.githubusercontent.com/assets/5554826/22395469/c919db8c-e582-11e6-9c40-bf24250f81ff.png">

**Comment by mmcbride1007** [comment]
Thanks for reporting. As you can tell in the README, this package is no longer supported since GitHub put out an official syntax theme for Atom. I recommend you check out [github-atom-light-syntax](https://atom.io/packages/github-atom-light-syntax).
